from dataclasses import dataclass
from enum import StrEnum


class ErrorCode(StrEnum):
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    DATABASE_RPC_REJECTED = "DATABASE_RPC_REJECTED"
    DATABASE_RESPONSE_INVALID = "DATABASE_RESPONSE_INVALID"
    JOB_LOCK_NOT_OWNED = "JOB_LOCK_NOT_OWNED"
    JOB_HEARTBEAT_TIMEOUT = "JOB_HEARTBEAT_TIMEOUT"
    JOB_CANCELLED = "JOB_CANCELLED"
    HANDLER_FAILED = "HANDLER_FAILED"
    BREEDING_HANDLER_NOT_CONFIGURED = "BREEDING_HANDLER_NOT_CONFIGURED"
    SAVE_WORKER_NOT_IMPLEMENTED = "SAVE_WORKER_NOT_IMPLEMENTED"
    WORKER_SHUTDOWN = "WORKER_SHUTDOWN"
    GAME_DATA_JSON_INVALID = "GAME_DATA_JSON_INVALID"
    GAME_DATA_JSONL_INVALID = "GAME_DATA_JSONL_INVALID"
    GAME_DATA_SCHEMA_INVALID = "GAME_DATA_SCHEMA_INVALID"
    GAME_DATA_SCHEMA_UNSUPPORTED = "GAME_DATA_SCHEMA_UNSUPPORTED"
    GAME_DATA_VALIDATION_FAILED = "GAME_DATA_VALIDATION_FAILED"
    GAME_DATA_VERSION_NOT_FOUND = "GAME_DATA_VERSION_NOT_FOUND"
    GAME_DATA_ARTIFACT_MISSING = "GAME_DATA_ARTIFACT_MISSING"
    GAME_DATA_HASH_MISMATCH = "GAME_DATA_HASH_MISMATCH"
    GAME_DATA_CACHE_CORRUPTED = "GAME_DATA_CACHE_CORRUPTED"
    GAME_DATA_CONFIGURATION_REQUIRED = "GAME_DATA_CONFIGURATION_REQUIRED"
    GAME_DATA_IMPORT_REJECTED = "GAME_DATA_IMPORT_REJECTED"


@dataclass(eq=False, slots=True)
class StructuredError(Exception):
    """Safe, stable error data that may cross the Repository/Worker boundary."""

    code: ErrorCode
    summary: str
    retryable: bool

    def __post_init__(self) -> None:
        self.summary = self.summary[:500]
        Exception.__init__(self, f"{self.code.value}: {self.summary}")
