package palooz

import "testing"

func FuzzDecompressBoundaries(f *testing.F) {
	f.Add(uint32(0))
	f.Add(uint32(1))
	f.Add(uint32(^uint32(0)))
	f.Fuzz(func(t *testing.T, declared uint32) {
		// The upstream decoder is intentionally isolated because it is not
		// fuzz-safe. This target exercises every Go/C ABI length guard without
		// sending attacker-generated bytes into the C++ core in the test process.
		_, _ = Decompress(nil, int(uint64(declared)))
	})
}
